updated task defintion

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -19,14 +19,11 @@ permissions:
   contents: read
 
 jobs:
-  # -------------------------------
-  # 1. Build & Push Docker Image
-  # -------------------------------
   build-and-push:
     name: Build & Push Docker Image
     runs-on: ubuntu-latest
     outputs:
-      image: ${{ steps.build-image.outputs.image }}
+      image: ${{ steps.push-image.outputs.image }}
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
@@ -43,29 +40,14 @@ jobs:
         uses: aws-actions/amazon-ecr-login@v1
 
       - name: Build and Push Docker Image
-        id: build-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_TAG: ${{ github.sha }}
+        id: push-image
         run: |
-          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
           echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
           docker build -t $IMAGE_URI .
           docker push $IMAGE_URI
-          echo "::add-mask::$IMAGE_URI"
           echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT
-          
-      - name: Debug Image URI
-        run: |
-          echo "IMAGE_URI: $IMAGE_URI"
-          if [ -z "$IMAGE_URI" ]; then
-            echo "❌ ERROR: Image URI is empty!"
-            exit 1
 
-
-  # -------------------------------
-  # 2. Deploy to ECS
-  # -------------------------------
   deploy:
     name: Deploy to ECS Fargate
     needs: build-and-push
@@ -81,7 +63,15 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
-      
+      - name: Debug Image URI
+        run: |
+          echo "IMAGE_URI: $IMAGE_URI"
+          if [ -z "$IMAGE_URI" ]; then
+            echo "❌ ERROR: Image URI is empty!"
+            exit 1
+          fi
+        env:
+          IMAGE_URI: ${{ needs.build-and-push.outputs.image }}
 
       - name: Render Task Definition
         id: render-task
