updated task defintion

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -55,6 +55,13 @@ jobs:
           echo "::add-mask::$IMAGE_URI"
           echo "image=$IMAGE_URI" >> $GITHUB_OUTPUT
           
+      - name: Debug Image URI
+        run: |
+          echo "IMAGE URI: ${{ needs.build-and-push.outputs.image }}"
+          if [ -z "${{ needs.build-and-push.outputs.image }}" ]; then
+            echo "❌ ERROR: Image URI is empty!"
+            exit 1
+
 
   # -------------------------------
   # 2. Deploy to ECS
